plink.exe -ssh houruomu@xcnd50.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd51.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd52.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd53.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd54.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd55.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd56.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd57.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd58.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd59.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
