plink.exe -ssh houruomu@xcnd50.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd51.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd52.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd53.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd54.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd55.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd56.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd57.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd58.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd59.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd60.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd0.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd1.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd2.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd3.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd4.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd5.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd6.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd7.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd8.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd9.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd0.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd10.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd11.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd12.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd13.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd14.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd15.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd16.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd17.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd18.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd19.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd20.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd20.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd21.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd22.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd23.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd24.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd25.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd26.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd27.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd28.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd29.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
plink.exe -ssh houruomu@xcnd61.comp.nus.edu.sg -pw ***REMOVED*** -m command.txt > output.txt
